### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1996-04-22",
  "email": "guswlsdl4808@gmail.com",
  "name": "name",
  "password": "1234",
  "phone": "01012345678"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=guswlsdl4808@gmail.com&code=5EClHjd3rk

### 로그인 (고객)
POST http://localhost:8081/signIn/customer
Content-Type: application/json

{
  "email": "guswlsdl4808@gmail.com",
  "password": "1234"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLRmx2NWFCdHUzb2lHV0tVcVFSNCt1ZmVqMS96NCtaR0pZQm4yZHA2d2dzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MDczNzgxMzMsImV4cCI6MTcwNzQ2NDUzM30._BzxcMZAo6xSZc7gaqAwvFLBsmnwYn0FAz9bxg3HWqg

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLRmx2NWFCdHUzb2lHV0tVcVFSNCt1ZmVqMS96NCtaR0pZQm4yZHA2d2dzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MDczNzgxMzMsImV4cCI6MTcwNzQ2NDUzM30._BzxcMZAo6xSZc7gaqAwvFLBsmnwYn0FAz9bxg3HWqg

{
  "from": "server",
  "message": "돈 충전",
  "money": 50000
}

#################################

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1996-04-22",
  "email": "guswlsdl4808@gmail.com",
  "name": "name",
  "password": "1234",
  "phone": "01012345678"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify?email=guswlsdl4808@gmail.com&code=67Vkm2soYC

### 로그인 (셀러)
POST http://localhost:8081/signIn/seller
Content-Type: application/json

{
  "email": "guswlsdl4808@gmail.com",
  "password": "1234"
}

